import type { NextPage } from "next";
import Head from "next/head";

import MyStory from "~/features/myStory";
import { MyWork } from "~/features/myWork";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyStory />
      {/*<MyWork />*/}
    </div>
  );
};

export default Home;
